language: python
python: 3.9
env:
  global:
  - LOCAL_REPO: sum-transformers
  - REMOTE_REPO: semitechnologies/sum-transformers
  # - secure: "nPppC13wULi/OEE9B0q59xdgbSqtGwn4RsjVz3FirkhaXJGphjUKVYdkEUrk7WvoZOkyEVvDAEWzD8H3RRCJmo4N5cgRodS+vfVonA/5TwakM+nKYOl8opV//egAz3NKRk8sjiAk+IlbHGqDPVKEdkP8JZWdF3SnQRACj8gtXb5RqjgXY1N8hU+vlh59GhmqnrgtAK/Mi7T+YHADJyoI8AFTtaeE+MptQhuTBbClNWT7J0divsNXZsU/71DB+2dCeQZ6sC7wd/vPQcsSJSSY+GnylhqWxIlLVpwYEzAZAFsuQeYANhIcspTZ2n8/hGxOhCpO6pPUAwKWx4Mqbdxw6eR0PLg+r03uGLW8aXTPTh7FItWNiNXybPvbdwUpUGKHKONlYy9Xw5j2+pjNvVE8ESSfwrw0PHtMGzACp41WG0DPSUnT8phr8D9DEJHXB7iTc0cA2h1cWJm5M0M3PDul7WrcsjC1j52ajD4Lv64jJFmBWZ7lV/pL8pEdjooL/eW16wkKQaSC/OKKU7kQSU5sL9McDQrg12o8/yF1kpaVu4G3thtWAdwN4ItzwdHUe0UzFsIagaiiZ+goW3b4TQ1NL6zpapt1dmyUekqOKE/vAm0oOcS/wjM+D7s2iA/WEbW1hovbWpAq7Uvj7bXrpQxCmOfRaSn9cUedBAExn+9uibo="
  # - secure: "sHx8LLbSbJHhNZdfTq9RMFWVn1vJ8Kr696ZdrveswE5oMuILWNnQJveJRhHdI7CF6+4lhD0VourQSJtWVV10k1l5TuJEz9oa0vYNqGg26nGVqg1t7Khp5/7fzVZIuooiT6FYc4Scts2zaaA1mmDR5qKWYa9Ik+vVvK1iI5ciLkTCXTIC0y80g6Y4g3E00R7R+PPEbENqtyAEnW6ZYW6phvgnsYMzkPg3YZyfKS68R6bhEZ7YMUICpGbQnx8DjbwQyMr58iPrnULJa560+m2jD+XtIYJdtHQ3Si3MHv2jVlJoKHSu6MVMqRW9c6KNVLRT2OkqWNe7CSRT9MTKe9GBCDsMdjX9ZQ7bdhHPaWeaGSAlRFuYTMCGT7DWsdVhyYXFtfQrdiGbiwbBMsmdGd1m7dhiliiaGZTJgWuFToHBIhhRocUgIzU34L1DYMGunZ0IjE6l7Yjmowtxio4kR9T8kmLfkLqewom5Uss1yspsiDvloMhRAuB4eTDSHIikWPA1u8c+RJIUJknxVLhyLPLmFHRBnfG+1DyerS6AB05jaucBcWhfAuuc0yVlSaUwJmcaoaI9vlE6SK6ljiLqJCB1aAxJMVIz6GwXi35m9N9uWKEsFoQCzGm5Y9F6912Hjn0p5Hh117K4M0scw7YdHwYfKX+Mgo7Gq06V5ZX1nKHvuD4="


install: echo skipping default travis install script
jobs:
  include:
    # always run test, etc. for this model
    - env:
        MODEL_NAME: google/pegasus-xsum
        MODEL_TAG_NAME: google-pegasus-xsum
      stage: buildanddeploy

    - env:
        MODEL_NAME: facebook/bart-large-cnn
        MODEL_TAG_NAME: facebook-bart-large-cnn
      stage: buildanddeploy


script:

- cicd/build.sh || travis_terminate 1

- cicd/test.sh || travis_terminate 1

- |-
  # Push docker image
  GIT_BRANCH=$TRAVIS_BRANCH \
  GIT_TAG=$TRAVIS_TAG \
  GIT_PULL_REQUEST=$TRAVIS_PULL_REQUEST \
  travis_wait 180 cicd/docker_push.sh || travis_terminate 1
before_install: 
  # install a newer docker version which supports buildx
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx

before_script:
  # login to docker at the very beginning, so we don't run into rate-limiting
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin


# currently the latest available - so we can install the latest docker
dist: bionic