name: Main

on:
  push:
    branches:
      - main
    tags:
      - '**'
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest-8-cores
    strategy:
      matrix:
        include:
          - model_name: facebook/bart-large-cnn
            model_tag_name: facebook-bart-large-cnn
            onnx_runtime: false
          - model_name: facebook/bart-large-cnn
            model_tag_name: facebook-bart-large-cnn
            onnx_runtime: true
          - model_name: google/pegasus-xsum
            model_tag_name: google-pegasus-xsum
            onnx_runtime: false
          # - model_name: google/pegasus-xsum
          #   model_tag_name: google-pegasus-xsum
          #   onnx_runtime: true
    env:
      LOCAL_REPO: sum-transformers
      REMOTE_REPO: semitechnologies/sum-transformers
      MODEL_NAME: ${{matrix.model_name}}
      MODEL_TAG_NAME: ${{matrix.model_tag_name}}
      ONNX_RUNTIME: ${{matrix.onnx_runtime}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Login to Docker Hub
        if: ${{ !github.event.pull_request.head.repo.fork }}
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build and test
        run: |
          cicd/build.sh || exit 1
          cicd/test.sh || exit 1
      - name: Deploy
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          export GIT_TAG=${GITHUB_REF##*/}
          cicd/docker_push.sh || exit 1
  build-custom-image:
    name: Build custom image
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    env:
      LOCAL_REPO: sum-transformers
      REMOTE_REPO: semitechnologies/sum-transformers
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Deploy
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          export GIT_TAG=${GITHUB_REF##*/}
          cicd/build_custom_base.sh || exit 1
